### ISSUE TITLE
Readme integration info out of date

### ISSUE THREAD

**Issue by microraptor** [sanghviharshit/ha-mila#1]
The information about the integration is out of date, because there is actually a native integration of Mila for Alexa and Google Home. See here: https://milacares.com/support.html#amazon-alexa

The Mila support staff also mentioned they implemented a HomeKit integration and will announce it this year.

BTW there a typo in line 31 of the readme: air auality

**Comment by sanghviharshit** [comment]
@microraptor thanks for pointing that out. It looks like they added it just a couple of months ago and I wasn't aware of that. I have updated the section in the Readme. 
However, from this discussion on [reddit](https://www.reddit.com/r/HomeKit/comments/lhp0qe/comment/gmyt68t/?utm_source=share&utm_medium=web2x&context=3), it looks like they are still not promising Homekit support for the first-gen devices and they will only be able to support it on the gen 2 devices. They mentioned adding Homekit support for gen 1 devices through Homebridge, which is great news in my opinion. This suggests they will have to make the API a little more public. So any changes to the API will have to be transparent and we can add new features by reusing some code from the homebridge plugin.

**Comment by microraptor** [comment]
[In their new update to that discussion the Mila support team actually says they will bring Homekit to all devices now.](https://old.reddit.com/r/HomeKit/comments/lhp0qe/mila_air_purifier_dev_says_theyre_working_on/hvfx6rk/?context=3) At least my understanding is that they managed to overcome the memory restrictions for gen 1 devices. But maybe "Homekit compatibility" also just means homebridge. I guess we have to wait for their announcement later this year. I don't know much about homekit, but I have heard it needs to work locally without internet for an official certification. So maybe we get an API directly from the Mila devices and we can connect them to HA without the cloud.

BTW thank you so much for taking the time to reverse engineer the API and put it in a library. You cannot imagine how happy it makes me and probably many others, who bought a Mila hoping to be able to get the sensor data manually and integrate it into HA etc.

**Comment by microraptor** [comment]
@sanghviharshit There is still the "air auality" typo in line 30 of the readme ;)

**Comment by dadcoachengineer** [comment]
Good work! Thank you 🙏🏻
