### ISSUE TITLE
Configuration via UI unsupported

### ISSUE THREAD

**Issue by pasternak** [sanghviharshit/ha-mila#13]
it seems after the recent update the configuration via UI is not working anymore.
I have tried removing mila from custom components, restarting ha, installing again, and restarting ha before adding again from integrations.

Always getting the same message: 

```
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```

<img width="554" alt="Screen Shot 2022-07-21 at 9 08 23 PM" src="https://user-images.githubusercontent.com/9785642/180361128-31d71fa7-c8cc-402e-98cc-4c22eccedc7d.png">

**Comment by sanghviharshit** [comment]
We introduced significant changes and it requires removing the existing integration, restarting HA, and adding Mila integration again. Let me know if you have the same issue after following the suggestion.

**Comment by pasternak** [comment]
have tried that, multiple times. always the same.

**Comment by pasternak** [comment]
I think I have found out the issue here:

2022-08-05 13:13:05 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration mila: No module named 'milasdk'

It does look like the dependencies from https://github.com/sanghviharshit/ha-mila/blob/8ed6332e7cfb754ef38af47af4ace022c69e3b9a/custom_components/mila/manifest.json#L6 has not been installed. after installing them all seems fine now. thanks!
