### ISSUE TITLE
Config flow not available

### ISSUE THREAD

**Issue by kammerdiener** [sanghviharshit/ha-mila#17]
Fresh install of the HACS integration and I am getting the following error when trying to add the integration: 
![image](https://user-images.githubusercontent.com/9094979/190656284-26e23b74-494a-4d94-9ea1-a3636921fb2e.png)

I am currently running:
Home Assistant 2022.8.7

This does not seem to be generating any log errors around this problem.

**Comment by sanghviharshit** [comment]
Did you try restarting Home Assistant before adding the Mila integration?

**Comment by kammerdiener** [comment]
It looks like removing and re-adding the integration fixed it. Not sure what was up with it.
