### ISSUE TITLE
distance_convert deprecated

### ISSUE THREAD

**Issue by Raithmir** [sanghviharshit/ha-mila#18]
Hi, just got my Mila yesterday, installed your integration and all working great! Thanks for your work!

I did notice an entry in the logs and thought I'd log it here...

> Detected integration that uses distance utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.DistanceConverter instead. Please report issue to the custom integration author for mila using this method at custom_components/mila/entities/location/distance_sensor.py, line 34: val = distance_convert(val, LENGTH_KILOMETERS, LENGTH_MILES)

**Comment by hallidaydaniel** [comment]
Noticed this also, the rest of the integration seems to work really well. I am guessing this is a small but also non-urgent change
