### ISSUE TITLE
Did Mila change the API again?

### ISSUE THREAD

**Issue by gminco** [sanghviharshit/ha-mila#20]
Yesterday I noticed this integration stopped updating the sensors, so I tried the phone app and noticed that I got logged out from it, I logged back in with no issues.

Since then, this integration hasn't worked, I tried reloading the integration yesterday and today and I get the following error:

`Log Details (WARNING)
Logger: homeassistant.config_entries
Source: config_entries.py:1088
First occurred: November 6, 2022 at 9:11:06 PM (2 occurrences)
Last logged: 8:43:28 AM

Config entry '******@*****.com' for mila integration not ready yet: Error communicating with API: Failed to get a valid response from Mila API service; Retrying in background`

Anyone else having the same issue?
I'm suspecting Mila made changes again on their end.

**Comment by dadcoachengineer** [comment]
I am noticing the same behavior. I have also noticed they seem to be having a lot of API issues over the past month. I wouldn't be surprised if they start filtering or rate limiting API calls.

**Comment by hallidaydaniel** [comment]
I had the same thing happen - I think that they expired all authorisation tokens. To resolve it I ended up deleting the integration, then re-adding it, with the same device names - everything now back in action.

Not sure if this would be resolved by working through the 'TODO' on sorting the config flow for oAuth tokens. 

I do think that there is clearly some other stuff going on at Mila - they have had quite a few issues with disconnects etc

**Comment by dadcoachengineer** [comment]
@hallidaydaniel - Thanks for posting this. Should have thought to do this as well. After deleting and adding the integration I am back in business.

**Comment by gminco** [comment]
Thanks, @hallidaydaniel!
I should've thought of that as well. It's working after removing/re-adding the integration.
This is definitely not an integration issue, so I'm closing this out.
