### ISSUE TITLE
CO2 not updating

### ISSUE THREAD

**Issue by shanelord01** [sanghviharshit/ha-mila#21]
I haven’t checked the other sensors but CO2 across my three Mila’s hasn’t budged from 411 since I installed the integration.

Anyone else experiencing this?

I’ve tried restarting the integration as well as uninstalling and reinstalling.

**Comment by sanghviharshit** [comment]
It looks fine on my side. Do you see the same data in the app as well?

**Comment by dadcoachengineer** [comment]
Having my Milas for a couple of years I really don't see the CO2 numbers changing much which from a health perspective is a good thing :)

**Comment by sanghviharshit** [comment]
Might be a faulty unit too. I see it change immediately when I'm cooking anything in the kitchen. My Mila is in the hallway on the same floor.
