### ISSUE TITLE
PM1 and Room AQI not showing up in HomeKit

### ISSUE THREAD

**Issue by toniolio** [sanghviharshit/ha-mila#29]
Using the HASS HomeKit Bridge and enabling all the sensors, everything else shows up fine (the fans, temp, humidity, CO, CO2, VOC, PM2.5 and PM10) but the PM1 and (indoor) "Room" AQI doesn't show up in HomeKit? Why might this be?

If this is obvious... apologies in advance. I'm new to Home Assistant and have not yet dived in deep enough to figure this out on my own — and wondering if there is something up that the integration author might want to be aware of. Or is this expected behaviour?

**Comment by sanghviharshit** [comment]
Here is what I found. 
PM1: The core only defines PM10 and PM2.5 sensor typed for Homekit (See https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_sensors.py#L203). So no PM1 is mapped to homekit yet. See this PR if you want to take a stab at adding it https://github.com/home-assistant/core/pull/46060

AQI: Core has a sensor type for AirQualitySensor, but the condition for this is the device_class needs to be `SensorDeviceClass.GAS`. The indoor AQI from Mila can't be mapped to a GAS type, so I'm not sure how to work around it. (See https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/accessories.py#L220)

**Comment by sanghviharshit** [comment]
Here is a similar problem someone raised, which might be helpful https://community.home-assistant.io/t/air-quality-sensor-in-homekit-bridge/277060
