### ISSUE TITLE
Auth token expiring frequently

### ISSUE THREAD

**Issue by M0LTE** [sanghviharshit/ha-mila#35]
Every few days my Mila auth token expires and I need to follow the 'reconfigure' flow, supplying my password.

Instead of this, assuming refresh tokens are not supported, I would prefer to entrust my password to the plugin, and for it to reauthenticate automatically.

**Comment by vsaintloup** [comment]
I don't think this is a bug from this integration; I believe it is something on Mila's end since every time this happened in HomeAssistant, I noticed that I have also been logged out from the Mila App on my iPhone and my iPad.

**Comment by sanghviharshit** [comment]
Yes, but if we store username, password like @M0LTE suggested, we can automatically login and get a new access token. It's on my TODO, but not finding much time. I'd welcome any PR of course if you'd like to contribute :)

**Comment by M0LTE** [comment]
Another reauth today. Don't have the HA experience to contribute a patch, sorry. I've just raised a ticket with Mila with the suggestion that they reach out to the plugin author to come up with a better solution for authentication.

**Comment by M0LTE** [comment]
Another reauth today.

**Comment by vsaintloup** [comment]
Yes, as Mila's servers were down today again for a few minutes, causing all the authentication tokens to expire. See messages I had with Mila earlier on.

> Kristoff Smith (Mila)
> Jan 26, 2024, 06:41 PST
> 
> Hi Vincent,
>  
> Thanks for getting in touch! Please note that a backend outage is currently causing Milas to appear offline in your app and affecting login abilities. Our team is hard at work investigating this and will share an update as soon as we have one.

> Livio (Mila)
> Jan 26, 2024, 06:55 PST
> 
> Hi Vincent,
>  
> Thanks for the heads up! All services are operational now. Please try logging into your Mila app and let me know if everything looks good.

**Comment by M0LTE** [comment]
Pretty pants.
I’ve made contact with Mila support and they’ve promised to engage their
dev team. I’ve send them a link to this issue. Here’s hoping.
