### ISSUE TITLE
Errors after server maintenance

### ISSUE THREAD

**Issue by aidenmitchell** [sanghviharshit/ha-mila#40]
Looks like something broke after their most recent server maintenance. I can't find any more helpful logs.

![image](https://github.com/user-attachments/assets/f82a0358-e861-4171-b1ee-44c029e695dc)

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 451, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mila/__init__.py", line 19, in async_setup_entry
    coordinator = MilaUpdateCoordinator(hass, entry)
  File "/config/custom_components/mila/update_coordinator.py", line 37, in __init__
    self._api = MilaApi(MilaConfigEntryAuth(hass, config_entry, MilaOauthImplementation(hass, config_entry)))
 ```

**Comment by vsaintloup** [comment]
Glad I found your opened issue, same issue here, I tried deleting the integration, restarting and re-adding it with no success.

**Comment by josephtweten** [comment]
I am experiencing the same

**Comment by timkrull** [comment]
Same here

**Comment by agravel** [comment]
+1

**Comment by Kelinni** [comment]
+1. I use my milas temperatures to handle equalizing the house with a helper's statical range between my basement mila and upstairs mila and enable my hvac fan based on these to decrease the delta. Plz fix <3

**Comment by zemerick1** [comment]
Using milasdk and the example script the following is observed:
```python
<<< {"errors":[{"message":"Validation error (FieldUndefined@[owner/appliances/smartModes]) : Field 'smartModes' in type 'Appliance' is undefined","locations":[{"line":27,"column":7}],"extensions":{"classification":"ValidationError"}}]}
Traceback (most recent call last):
  File "C:\Users\Zak\Documents\Code\milasdk\lib\site-packages\milasdk\api.py", line 62, in _execute
    return await session.execute(document, variable_values)
  File "C:\Users\Zak\Documents\Code\milasdk\lib\site-packages\gql\client.py", line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': "Validation error (FieldUndefined@[owner/appliances/smartModes]) : Field 'smartModes' in type 'Appliance' is undefined", 'locations': [{'line': 27, 'column': 7}], 'extensions': {'classification': 'ValidationError'}}

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\Users\Zak\Documents\Code\milasdk\main.py", line 36, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\Zak\Documents\Code\milasdk\main.py", line 32, in main
    await update(api)
  File "c:\Users\Zak\Documents\Code\milasdk\main.py", line 16, in update
    r = await api.get_appliances()
  File "C:\Users\Zak\Documents\Code\milasdk\lib\site-packages\milasdk\api.py", line 126, in get_appliances
    result = await self._execute(query)
  File "C:\Users\Zak\Documents\Code\milasdk\lib\site-packages\milasdk\api.py", line 78, in _execute
    raise MilaError("Transport reported query error") from ex
milasdk.exceptions.MilaError: Transport reported query error
```

**Comment by zemerick1** [comment]
Until author has fixed it correctly for the API change if you navigate to the site-packages directory and edit milasdk/gql/queries.py
https://github.com/simbaja/milasdk/blob/master/milasdk/gql/queries.py

Comment out lines 31-40

```python
        ds.Appliance.smartModes.select(
            ds.SmartModes.quiet.select(ds.QuietMode.isEnabled),
            ds.SmartModes.housekeeper.select(ds.HousekeeperMode.isEnabled),
            ds.SmartModes.quarantine.select(ds.QuarantineMode.isEnabled),
            ds.SmartModes.sleep.select(ds.SleepMode.isEnabled),
            ds.SmartModes.turndown.select(ds.TurndownMode.isEnabled),
            ds.SmartModes.whitenoise.select(ds.WhitenoiseMode.isEnabled),
            ds.SmartModes.powerSaver.select(ds.PowerSaverMode.isEnabled),
            ds.SmartModes.childLock.select(ds.ChildLockMode.isEnabled)
        ),
```

If you're using Home Assistant in a docker container you must be in the container before you edit the file at:
```
/usr/local/lib/python3.12/site-packages/milasdk/gql
```
After which you will need to restart Home Assistant.

**Comment by itbeemer** [comment]
+1

**Comment by dadcoachengineer** [comment]
Excellent debugging @zemerick1

Thank you!

**Comment by marcthespot0** [comment]
> Until author has fixed it correctly for the API change if you navigate to the site-packages directory and edit milasdk/gql/queries.py https://github.com/simbaja/milasdk/blob/master/milasdk/gql/queries.py
> 
> Comment out lines 31-40
> 
> ```python
>         ds.Appliance.smartModes.select(
>             ds.SmartModes.quiet.select(ds.QuietMode.isEnabled),
>             ds.SmartModes.housekeeper.select(ds.HousekeeperMode.isEnabled),
>             ds.SmartModes.quarantine.select(ds.QuarantineMode.isEnabled),
>             ds.SmartModes.sleep.select(ds.SleepMode.isEnabled),
>             ds.SmartModes.turndown.select(ds.TurndownMode.isEnabled),
>             ds.SmartModes.whitenoise.select(ds.WhitenoiseMode.isEnabled),
>             ds.SmartModes.powerSaver.select(ds.PowerSaverMode.isEnabled),
>             ds.SmartModes.childLock.select(ds.ChildLockMode.isEnabled)
>         ),
> ```
> 
> If you're using Home Assistant in a docker container you must be in the container before you edit the file at:
> 
> ```
> /usr/local/lib/python3.12/site-packages/milasdk/gql
> ```
> 
> After which you will need to restart Home Assistant.

I don't seem to have the location /usr/local/lib/python3.12/site-packages/milasdk/gql but it is referenced in the error my logs. I have the Home Assistant Green. Any help would be appreciated. On what location I can find this file to edit.

**Comment by dadcoachengineer** [comment]
> > Until author has fixed it correctly for the API change if you navigate to the site-packages directory and edit milasdk/gql/queries.py https://github.com/simbaja/milasdk/blob/master/milasdk/gql/queries.py
> > Comment out lines 31-40
> > ```python
> >         ds.Appliance.smartModes.select(
> >             ds.SmartModes.quiet.select(ds.QuietMode.isEnabled),
> >             ds.SmartModes.housekeeper.select(ds.HousekeeperMode.isEnabled),
> >             ds.SmartModes.quarantine.select(ds.QuarantineMode.isEnabled),
> >             ds.SmartModes.sleep.select(ds.SleepMode.isEnabled),
> >             ds.SmartModes.turndown.select(ds.TurndownMode.isEnabled),
> >             ds.SmartModes.whitenoise.select(ds.WhitenoiseMode.isEnabled),
> >             ds.SmartModes.powerSaver.select(ds.PowerSaverMode.isEnabled),
> >             ds.SmartModes.childLock.select(ds.ChildLockMode.isEnabled)
> >         ),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you're using Home Assistant in a docker container you must be in the container before you edit the file at:
> > ```
> > /usr/local/lib/python3.12/site-packages/milasdk/gql
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After which you will need to restart Home Assistant.
> 
> I don't seem to have the location /usr/local/lib/python3.12/site-packages/milasdk/gql but it is referenced in the error my logs. I have the Home Assistant Green. Any help would be appreciated. On what location I can find this file to edit.

If you are running HAOS, you will need to get a bash shell on the homeassistant container.

If you have the 'Advanced SSH & Web Terminal" add-on installed you can run the following docker command:

exec -it homeassistant bash

Then you should be able to use vi to edit /usr/local/lib/python3.12/site-packages/milasdk/gql/queries.py

**Comment by marcthespot0** [comment]
> > > Until author has fixed it correctly for the API change if you navigate to the site-packages directory and edit milasdk/gql/queries.py https://github.com/simbaja/milasdk/blob/master/milasdk/gql/queries.py
> > > Comment out lines 31-40
> > > ```python
> > >         ds.Appliance.smartModes.select(
> > >             ds.SmartModes.quiet.select(ds.QuietMode.isEnabled),
> > >             ds.SmartModes.housekeeper.select(ds.HousekeeperMode.isEnabled),
> > >             ds.SmartModes.quarantine.select(ds.QuarantineMode.isEnabled),
> > >             ds.SmartModes.sleep.select(ds.SleepMode.isEnabled),
> > >             ds.SmartModes.turndown.select(ds.TurndownMode.isEnabled),
> > >             ds.SmartModes.whitenoise.select(ds.WhitenoiseMode.isEnabled),
> > >             ds.SmartModes.powerSaver.select(ds.PowerSaverMode.isEnabled),
> > >             ds.SmartModes.childLock.select(ds.ChildLockMode.isEnabled)
> > >         ),
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If you're using Home Assistant in a docker container you must be in the container before you edit the file at:
> > > ```
> > > /usr/local/lib/python3.12/site-packages/milasdk/gql
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After which you will need to restart Home Assistant.
> > 
> > 
> > I don't seem to have the location /usr/local/lib/python3.12/site-packages/milasdk/gql but it is referenced in the error my logs. I have the Home Assistant Green. Any help would be appreciated. On what location I can find this file to edit.
> 
> If you are running HAOS, you will need to get a bash shell on the homeassistant container.
> 
> If you have the 'Advanced SSH & Web Terminal" add-on installed you can run the following docker command:
> 
> exec -it homeassistant bash
> 
> Then you should be able to use vi to edit /usr/local/lib/python3.12/site-packages/milasdk/gql/queries.py

<img width="454" alt="image" src="https://github.com/user-attachments/assets/c139b7f1-f486-4cda-95d9-fa000ac35b6e">
I don't have that path

**Comment by TomBrien** [comment]
you need to run `docker exec -it homeassistant bash` first to get into the homeassistant container

**Comment by Kelinni** [comment]
> `docker exec -it homeassistant bash` by @TomBrien 

This is fire!  as someone who works in a tehcnical world and knows what docker is but doesn't have much experience this is the comment that solved my final blockage!

A massive and huge thanks to @zemerick1 for doing the heavy liften and exceptional debugging!


For anyone else trying to make sense of all the previous (really honestly amazing comments and help) but having a hard time and just need basic instructions here is what I did:

1. Using the "Advanced SSH & Web Terminal" addon in my HomeAssistant I openned terminal in HA. (you need to turn protected mode off if you havent already.  Feel free to turn it back on after. I know i did)
2. Navigate to the mila directory where the queries file is located `cd /usr/local/lib/python3.12/site-packages/milasdk/gql`
3. Make a backup `cp queries.py queries.py.bak` because it's a good idea
4. You're going to use vi to edit the queries.py file.  In case you haven't used vi before follow the next set of steps.  The final result should look like below.
5. Once done the vi editting restart HomeAssistant.

Vi cheat sheet

1. open the queries.py file with vi `vi queries.py`
2. Press the letter `i` on your keyboard to enter into insert mode
3. Use the arrow keys on your keyboard to navigate to lines 31-40 as shown below "Appliance.smartModes.select" is what I looked for.
4. At the beginning of each of each line press `#` to add a hash symbol (the comment symbol for python)
5. When all the lines (iuncluding the final ")," have the # at the beginning press `esc` on your keyboard then type `:wq` to write and quite vi. (if you do something bad in the file you can always start this over again by pressing `esc` a couple times then type `:q!` to force quit vi without saving your changes.

Final result
`#        ds.Appliance.smartModes.select(
#            ds.SmartModes.quiet.select(ds.QuietMode.isEnabled),
#            ds.SmartModes.housekeeper.select(ds.HousekeeperMode.isEnabled),
#            ds.SmartModes.quarantine.select(ds.QuarantineMode.isEnabled),
#            ds.SmartModes.sleep.select(ds.SleepMode.isEnabled),
#            ds.SmartModes.turndown.select(ds.TurndownMode.isEnabled),
#            ds.SmartModes.whitenoise.select(ds.WhitenoiseMode.isEnabled),
#            ds.SmartModes.powerSaver.select(ds.PowerSaverMode.isEnabled),
#            ds.SmartModes.childLock.select(ds.ChildLockMode.isEnabled)
#        ),`

**Comment by Kelinni** [comment]
> `docker exec -it homeassistant bash` by @TomBrien 

This is fire!  as someone who works in a tehcnical world and knows what docker is but doesn't have much experience this is the comment that solved my final blockage!

A massive and huge thanks to @zemerick1 for doing the heavy liften and exceptional debugging!


For anyone else trying to make sense of all the previous (really honestly amazing comments and help) but having a hard time and just need basic instructions here is what I did:

1. Using the "Advanced SSH & Web Terminal" addon in my HomeAssistant I openned terminal in HA. (you need to turn protected mode off if you havent already.  Feel free to turn it back on after. I know i did)
2. enter into docker with `docker exec -it homeassistant bash` (this won't work if you have protected mode on and using the addon)
3. Navigate to the mila directory where the queries file is located `cd /usr/local/lib/python3.12/site-packages/milasdk/gql`
4. Make a backup `cp queries.py queries.py.bak` because it's a good idea
5. You're going to use vi to edit the queries.py file.  In case you haven't used vi before follow the next set of steps.  The final result should look like below.
6. Once done the vi editting restart HomeAssistant.

Vi cheat sheet

1. open the queries.py file with vi `vi queries.py`
2. Press the letter `i` on your keyboard to enter into insert mode
3. Use the arrow keys on your keyboard to navigate to lines 31-40 as shown below "Appliance.smartModes.select" is what I looked for.
4. At the beginning of each of each line press `#` to add a hash symbol (the comment symbol for python)
5. When all the lines (iuncluding the final ")," have the # at the beginning press `esc` on your keyboard then type `:wq` to write and quite vi. (if you do something bad in the file you can always start this over again by pressing `esc` a couple times then type `:q!` to force quit vi without saving your changes.

Final result
![Screenshot 2024-08-08 154633](https://github.com/user-attachments/assets/1d8eb61e-9aa5-4afe-9fbb-e85e8dbae3d8)

**Comment by TomBrien** [comment]
You should know that if you're running HAOS, the package will likely get reinstalled on HA updates and these changes will need repeating

**Comment by marcthespot0** [comment]
If I am on home assistant core is there away to find this file?

**Comment by marcthespot0** [comment]
> If I am on home assistant core is there away to find this file?

any suggestions since my HA does not use docker?

**Comment by Kelinni** [comment]
> > If I am on home assistant core is there away to find this file?
> 
> any suggestions since my HA does not use docker?

I'm far from an expert, but since HAOS is just a managed docker instance, i would assume that HA Core is what is running inside.  So just follow my steps starting at number 3.  `cd /usr/local/lib/python3.12/site-packages/milasdk/gql`

**Comment by gaillal** [comment]
> > > If I am on home assistant core is there away to find this file?
> > 
> > 
> > any suggestions since my HA does not use docker?
> 
> I'm far from an expert, but since HAOS is just a managed docker instance, i would assume that HA Core is what is running inside. So just follow my steps starting at number 3. `cd /usr/local/lib/python3.12/site-packages/milasdk/gql`

Unfortunately the folder pythons3.12 does not exist on HA core running on a green box. Any ideas where the access the file to be updated.  Thanks.

**Comment by gaillal** [comment]
> If I am on home assistant core is there away to find this file?

Did you find a solution?

**Comment by marcthespot0** [comment]
> > If I am on home assistant core is there away to find this file?
> 
> Did you find a solution?

I did not, I am in the same boat as you. I do not have python3.12 under /usr/local/lib, and there is no docker containers running on HASS Core.

**Comment by zemerick1** [comment]
> > > If I am on home assistant core is there away to find this file?
> > 
> > 
> > Did you find a solution?
> 
> I did not, I am in the same boat as you. I do not have python3.12 under /usr/local/lib, and there is no docker containers running on HASS Core.

3.12 is the version of python the box is running. Use python -V or python3 -V to find the version you are using then navigate to that folder. ie: /usr/local/lib/pythonX.YY/site-packages/

**Comment by marcthespot0** [comment]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/541da398-8b02-449e-837b-6ace67a12d3d">
I don't even have the Python folders.

**Comment by gaillal** [comment]
> <img alt="image" width="493" src="https://private-user-images.githubusercontent.com/92120709/358300703-541da398-8b02-449e-837b-6ace67a12d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDMwODEsIm5iZiI6MTcyMzc0Mjc4MSwicGF0aCI6Ii85MjEyMDcwOS8zNTgzMDA3MDMtNTQxZGEzOTgtOGIwMi00NDllLTgzN2ItNmFjZTY3YTEyZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzE5NDEzNTY2M2E5ZjM0MTEzZjAyZjYxNTNiNjc5NjJmY2I1YTc0M2IyM2Y5YTI0YjYyMTI3Njk2NDQ3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FEmBUV_zt9Y_nwZ8wQLy5h_SLfECnHzOJUjQsxSa-EE"> I don't even have the Python folders.

Same issue here. The lib folder only contains two files and no folder.

**Comment by omar-merhebi** [comment]
So the directory `/usr/lib` contains the contains the python3.12 directory, however under `site-packages`, there is no `milasdk` directory:

```
site-packages # pwd
/usr/lib/python3.12/site-packages
site-packages # ls
PyYAML-6.0.1.dist-info             awake                              pathspec                           pulsemixer-1.5.1.dist-info         yaml
PyYAML.libs                        awake-1.0-py3.12.egg-info          pathspec-0.12.1.dist-info          pyparsing                          yamllint
README.txt                         distutils-precedence.pth           pip                                pyparsing-3.1.2.dist-info          yamllint-1.35.1.dist-info
_distutils_hack                    packaging                          pip-24.0-py3.12.egg-info           setuptools
_yaml                              packaging-24.0.dist-info           pkg_resources                      setuptools-69.5.1-py3.12.egg-info
```

**Comment by omar-merhebi** [comment]
UPDATE: I found it. You need to open the docker environment INSIDE home assistant when running HA Core. Ensure Advanced Mode is enabled in your profile and **turn off protection mode for the SSH addon**. Then via ssh run the following:

`docker exec -it homeassistant /bin/bash`

If you go back to `/usr/local/lib/` you will find the python3.12 directory and the relevant subdirectories.

**Comment by gaillal** [comment]
> UPDATE: I found it. You need to open the docker environment INSIDE home assistant when running HA Core. Ensure Advanced Mode is enabled in your profile and **turn off protection mode for the SSH addon**. Then via ssh run the following:
> 
> `docker exec -it homeassistant /bin/bash`
> 
> If you go back to `/usr/local/lib/` you will find the python3.12 directory and the relevant subdirectories.

This seems to be applicable to instance of Home Assistant running in a docker container, but doesn’t address the issue experienced running HA on a green box for example…

**Comment by omar-merhebi** [comment]
> > UPDATE: I found it. You need to open the docker environment INSIDE home assistant when running HA Core. Ensure Advanced Mode is enabled in your profile and **turn off protection mode for the SSH addon**. Then via ssh run the following:
> > `docker exec -it homeassistant /bin/bash`
> > If you go back to `/usr/local/lib/` you will find the python3.12 directory and the relevant subdirectories.
> 
> This seems to be applicable to instance of Home Assistant running in a docker container, but doesn’t address the issue experienced running HA on a green box for example…

I am running HA on an NUC not using docker. From what I was understanding home assistant uses docker containers with HAOS to manage environments.

**Comment by gaillal** [comment]
> I am running HA on an NUC not using docker. From what I was understanding home assistant uses docker containers with HAOS to manage environments.

Thanks for the feedback. I’ve previously tried to run the discussed docker command, but received the error below. On the other hand, I may not be running the command correctly…

![Screenshot 2024-08-22 185435](https://github.com/user-attachments/assets/03dc5c3b-15d9-4c51-9109-81726063b88f)

**Comment by marcthespot0** [comment]
> > I am running HA on an NUC not using docker. From what I was understanding home assistant uses docker containers with HAOS to manage environments.
> 
> Thanks for the feedback. I’ve previously tried to run the discussed docker command, but received the error below. On the other hand, I may not be running the command correctly…
> 
> ![Screenshot 2024-08-22 185435](https://private-user-images.githubusercontent.com/23727977/360728677-03dc5c3b-15d9-4c51-9109-81726063b88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDUxNTYsIm5iZiI6MTcyNDcwNDg1NiwicGF0aCI6Ii8yMzcyNzk3Ny8zNjA3Mjg2NzctMDNkYzVjM2ItMTVkOS00YzUxLTkxMDktODE3MjYwNjNiODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDIwNDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYWQ3ZDY2NGEzZDljNTIzYjZlNWZmM2I3YTYyMzhlNDkyMzg1ZTgzZGI5MjhlNzVkMzYwYWM5ZjRiYzE4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iuEk0Esmbvjovd5pL0mvnzwleJGtbYQJYKavr9mnEKk)

any luck figuring this out?

**Comment by TomBrien** [comment]
As I got tired of commenting out the lines on every update and this project seems to sadly be dead. I have forked the python package and made the changes so the integration can point to that library instead.

**THIS IS DONE WITH NO INTENTION OF SUPPORT OR UPDATES. If it breaks, it breaks.**

To switch to using this. In `configuration/custom_components/mila/manifest.json` change `"milasdk==0.4.4",` to `"milasdklite==0.0.2",`. Then restart Home Assistant.

**Comment by vsaintloup** [comment]
@TomBrien works like a charm — great idea, thank you!

**Comment by gaillal** [comment]
@TomBrien thank you!

**Comment by DSteiNeuro** [comment]
@TomBrien Thank you!
Took a couple of reloads but did the trick!

**Comment by M0LTE** [comment]
PRs done, action required from @simbaja and then @sanghviharshit to close this.
