### ISSUE TITLE
Not returning correct list of Mila devices

### ISSUE THREAD

**Issue by ReplicaObscura** [sanghviharshit/ha-mila#5]
Hello!

I'm not sure if this is an issue with this integration or with my Mila account. I have 4 Mila devices, and this integration detects 4 devices, but 2 of them control the exact same Mila and none of them control my 4th unit.

Wondering if you might have any troubleshooting tips, or if this is something I will need to work with Mila to correct in my account in some way? Thanks!

**Comment by ReplicaObscura** [comment]
Upon further investigation, the air quality readings seem to be from the correct units, but the switches for controlling the various features from two different units control the same unit.

**Comment by sanghviharshit** [comment]
Hi @bmcclure I only have a single Mila device to test with, but I have noticed that it's a little confusing if you have multiple devices. Most of the switches are common to the account and control all the devices on the account. There is only one switch available for "per device" control. But for simplicity and to mimic Mila App interface, I expose all the switches for each device. So if you toggle a switch from a device that's common for the account, it should toggle the state for switches in other devices. (Might take a minute for the refresh). 
If you are seeing different behavior, then there might be some additional API calls or information the Mila app might be passing to control devices separately, but I can't capture them as I only have a single device.

Reference:
```
ACCOUNT_SWITCH_TYPES = {
    "house_keeper_mode": [
        "House Keeper Mode",
    ],
    "turn_down_service": [
        "Turn Down Service",
    ],
    "sleep_mode": [
        "Sleep Mode",
    ],
    "whitenoise_mode": [
        "Whitenoise Mode",
    ],
    "quarantine": [
        "Quarantine",
    ],
    "quiet_zone": [
        "Quiet Mode",
    ],
}

DEVICE_SWITCH_TYPES = {
    "sounds_enabled": [
        "Sounds Enabled",
    ],
}
```

**Comment by ReplicaObscura** [comment]
Interesting! In the Mila app you can definitely control all of those options per-device, and in fact I don't think it's even possible through the official app to control them all at once.

Perhaps this is something I can look into testing since I have 4 Milas. Out of curiosity how are you figuring out the API, sniffing the app traffic?

While I often want the same settings on all of my Milas, that's not always the case: I have Sleep mode and Turndown service enabled in the Bedroom, but not the other rooms, for example.

**Comment by sanghviharshit** [comment]
Yes, sniffing the app traffic. But it's very tricky and the iPhone I use to sniff traffic from is too old, so it's stuck on a very old version of the Mila app from the App store. See https://blog.sanghviharshit.com/reverse-engineering-private-api-ssl-pinning/

**Comment by sanghviharshit** [comment]
This should be fixed by the latest commits as we moved to a new SDK. Please let me know if it's still an issue.
