### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by christensenjames** [sanghviharshit/ha-mila#7]
First of all, I want to say thank you for your hard work on this integration. Mila was one of the biggest missing pieces for me in Home Assistant.

The integration was working flawlessly for me since you released it, until yesterday, when both of my Milas became unavailable. I reloaded the integration hoping it would fix the issue, but it didn't. Tonight, I updated to Home Assistant Core 2022.6, uninstalled the integration and reinstalled it, but am unable to login with the correct credentials.

Any insight? Thanks again.

**Comment by christensenjames** [comment]
Here's an error in the log upon login attempt:

> This error originated from a custom integration.
> 
> Logger: custom_components.mila.config_flow
> Source: custom_components/mila/config_flow.py:73
> Integration: Mila (documentation, issues)
> First occurred: 11:01:05 PM (2 occurrences)
> Last logged: 11:06:01 PM
> 
> Status: 500, Error Message: Error with get https://api.milacares.com/mms/appliances/meta
> Status: 500, Error Message: Error with get https://id.milacares.com/auth/realms/prod/protocol/openid-connect/auth

**Comment by hendrer** [comment]
I can confirm same issue here

**Comment by gminco** [comment]
I'm having the same issue as well, it has been working great until yesterday, maybe Mila changed something on their end?
My Mila phone app and authentication on their web site is working fine though.

**Comment by sanghviharshit** [comment]
This happened to me when I upgraded Home Assistant. Not sure if it's HA or Mila. I will try to debug it today.

**Comment by yyli** [comment]
Just adding some more color. It seems like Mila might have changed their API address. Going to `https://api.milacares.com/mms/appliances/meta` directly in the browser gets 502 when it didn't used to

**Comment by sanghviharshit** [comment]
So the good news is  - it looks like the login flow still works, but the APIs for profile and device information has changed. The bad news is they have moved to graphql and it is not a simple API route change. It will require a lot of code change as we'll have to integrate a graphql client. I doubt I can do this anytime soon, but I'll be happy to help if anyone is interested in working on this.

**Comment by sanghviharshit** [comment]
Here is the graphql endpoint - https://api.milacares.com/graphql. (You can get the authorization token from Home Assistant -> /config/.storage/core.config_entries and find the user_token under the config for mila)
Here is the SDL of the schema I exported - https://gist.github.com/sanghviharshit/8959088d950f4cff1dfd8c668848b1d9

**Comment by asucrews** [comment]
Not sure if I have time to help, but I look in more in to it this weekend.
Below is python package that will help out
(https://github.com/graphql-python/gql/blob/master/docs/code_examples/aiohttp_async_dsl.py)    

Look at garphicgl over the weekend, it over my pay grade :(

**Comment by adanydev** [comment]
I spent some time looking at the old Gist and updating it to use GraphQL:
https://gist.github.com/adanydev/f0735eab0676f4d1ed681d3a52c6a4c6 

It's pretty rough right now, but it at least works and gets the data back. I started looking over the main code in this repo, and it definitely seems like the objects had changed in addition to the service (unsurprisingly). This is my first time working on an integration with HA so I'm not familiar with how to actually test changes in the integration. Happy to keep helping with it if there's some guidance on that part.

**Comment by dadcoachengineer** [comment]
"Backend changes to lay the groundwork for future features" is likely what broke @sanghviharshit integration :(

I am hoping this means they may have an public API available at some point...

![image](https://user-images.githubusercontent.com/6666082/177556839-fc2d5a22-b793-4c00-a486-7b859b9f9d1e.png)

**Comment by marcthespot0** [comment]
Hi All, to confirm there is no longer a way to get Mila working with HA?  Or is what adanydev posted the fix for now?

**Comment by asucrews** [comment]
@marcthespot0 I think what @adanydev posted get the data from the new API, what is left is the Dev time and skills to update the integration

**Comment by marcthespot0** [comment]
@asucrews OK, I see that code but what do I do with it?

**Comment by asucrews** [comment]
@marcthespot0 if I knew that I would update the integration :(

**Comment by adanydev** [comment]
I’ve spent some time looking over the integration and can probably put some more time into it this week. I’ll also need to double check that they didn't make API changes since my Gist work.

**Comment by marcthespot0** [comment]
Thanks, guys - @adanydev hope you find the time to figure it out.  :) Good luck

**Comment by sanghviharshit** [comment]
Update - @simbaja put a lot of time into creating an SDK for the graphql API - https://github.com/simbaja/milasdk and integrating this into ha-mila. @simbaja 's PR https://github.com/sanghviharshit/ha-mila/pull/12 is a huge refactor from the original code I wrote. So after some discussion, we have decided to add @simbaja as a contributor to this repo, while the SDK can stay as a separate project that @simbaja will own and I will be added as a contributor there and a maintainer on pypi.

**Comment by dadcoachengineer** [comment]
Team....thank you all so much for your hard work on refactoring the graphql API into this integration! Hoping that Mila sticks with this for a while :)

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/6666082/180209086-228cac80-f869-4414-b64a-e8a83e77d39b.png">
